package com.jurtz.android.ichhabnochnie.message;

import java.util.HashSet;

/**
 * Laden der Nachrichten zum Datenbank-Aufbau
 */
public class MessageHelper {

    // Initialisiere Texte
    public static HashSet<Message> getMessages() {
        HashSet<Message> messages = new HashSet<>();
        String date = "2016-05-27";
        String date2 = "2016-05-31";
		String date3 = "2016-07-12";
        String user = "SYSTEM";

        messages.add(new Message("24 Stunden am Stück vor dem Fernseher verbracht",date2, user));
        messages.add(new Message("Alkohol getrunken",date2,user));
		messages.add(new Message("american Football gespielt",date3,user));
        messages.add(new Message("an einem Casting teilgenommen",date2,user));
        messages.add(new Message("an einen elektrischen Zaun gepinkelt",date2,user));
        messages.add(new Message("an einer Wand gelauscht, um andere beim Sex zu hören",date2,user));
        messages.add(new Message("Analsex gehabt",date,user));
        messages.add(new Message("auf 4chan gebrowsed",date2,user));
        messages.add(new Message("auf der Arbeit Alkohol getrunken",date2,user));
		messages.add(new Message("auf einem Festival meine Brüste gezeigt",date3,user));
        messages.add(new Message("auf einem Tisch getanzt",date,user));
		messages.add(new Message("auf Steam ein Spiel gekauft und es nie gespielt",date3,user));
		messages.add(new Message("Baseball gespielt",date3,user));
        messages.add(new Message("bei diesem Spiel etwas herausgefunden, was ich lieber nicht gewusst hätte",date,user));
		messages.add(new Message("bei diesem Spiel gelogen",date,user));
        messages.add(new Message("bei einem ernsten Gespräch anfangen müssen, zu lachen",date2,user));
		messages.add(new Message("bei einer Achterbahnfahrt gekotzt",date3,user));
        messages.add(new Message("bei einer Orgie mitgemacht",date,user));
        messages.add(new Message("bei einer Prüfung geschummelt",date,user));
        messages.add(new Message("bei einer Sex-Hotline angerufen",date2,user));
		messages.add(new Message("bei einer Talentshow mitgemacht",date3,user));
        messages.add(new Message("beim Aufwachen nicht mehr gewusst, wo ich war",date2,user));
        messages.add(new Message("beim Beerpong gewonnen",date,user));
		messages.add(new Message("beim Beerpong verloren",date3,user));
        messages.add(new Message("beim Flunkyball gewonnen",date,user));
		messages.add(new Message("beim Flunkyball verloren",date3,user));
        messages.add(new Message("beim Rummachen mit meinem Partner an jemand anderen gedacht",date2,user));
        messages.add(new Message("beim Schwimmen Teile meiner Bekleidung verloren",date,user));
        messages.add(new Message("beim Sex Alltagsprobleme diskutiert",date2,user));
        messages.add(new Message("beim Sex den falschen Namen gerufen",date,user));
        messages.add(new Message("beim Sex den Großteil meiner Klamotten angelassen",date2,user));
        messages.add(new Message("beim Sex gekotzt",date,user));
        messages.add(new Message("beim Sex jemandem gesagt, was er/sie zu tun hat",date,user));
        messages.add(new Message("beim Speeddating mitgemacht",date2,user));
        messages.add(new Message("beim Telefonieren masturbiert",date2,user));
		messages.add(new Message("beim Versuch, Analsex zu haben versagt",date3,user));
		messages.add(new Message("betrunken ein Referat gehalten",date3,user));
        messages.add(new Message("bezüglich meines Gewichts um bis zu 20kg gelogen",date2,user));
		messages.add(new Message("Bisasam als Starterpokémon gewählt",date3,user));
        messages.add(new Message("blöde Trinkspiele gespielt",date,user));
        messages.add(new Message("Bungee Jumping gemacht",date,user));
		messages.add(new Message("Cola getrunken obwohl auch Alkohol da gewesen wäre",date3,user));
		messages.add(new Message("Crocs getragen",date3,user));
        messages.add(new Message("daran gedacht, auszuwandern",date2,user));
        messages.add(new Message("darauf gewartet, dass endlich jemand vorschlägt, nackt weiterzuspielen",date2,user));
        messages.add(new Message("den Dildo von jemand anderem benutzt",date,user));
        messages.add(new Message("den falschen Kraftstoff getankt",date2,user));
        messages.add(new Message("den Geburtstag eines Familienangehörigen vergessen",date2,user));
        messages.add(new Message("den \"nackten Mann\" gemacht",date,user));
		messages.add(new Message("den Superbowl gesehen",date3,user));
        messages.add(new Message("denselben Film mehrmals im Kino gesehen",date,user));
        messages.add(new Message("die Anfrage meines Chefs auf Facebook ignoriert",date2,user));
        messages.add(new Message("die Brüste des nächsten Mädchens links von mir gesehen",date,user));
        messages.add(new Message("die Eltern eines Freundes / einer Freundin beim Sex gehört",date2,user));
        messages.add(new Message("die Mitspielerin mit den größten Brüsten geküsst",date,user));
        messages.add(new Message("die Person links von mir nackt gesehen",date,user));
        messages.add(new Message("die Person rechts von mir nackt gesehen",date,user));
        messages.add(new Message("dieses Spiel gespielt",date,user));
        messages.add(new Message("drei Abende am Stück einen Vollrausch gehabt",date2,user));
        messages.add(new Message("ein befreundetes Pärchen nach einem Vierer gefragt",date2,user));
        messages.add(new Message("ein Bett kaputt gemacht",date,user));
		messages.add(new Message("ein Buch an einem Tag gelesen",date3,user));
        messages.add(new Message("ein Buch gelesen, das mich richtig angeturnt hat",date2,user));
        messages.add(new Message("ein Buch gelesen, obwohl ich es ekelhaft fand",date2,user));
        messages.add(new Message("ein Date frühzeitig beendet",date2,user));
        messages.add(new Message("ein Date gehabt, nur um einer anderen Person weh zu tun",date2,user));
        messages.add(new Message("ein Fahrrad geklaut",date2,user));
        messages.add(new Message("ein Kompliment für meine Geschlechtsteile bekommen",date2,user));
        messages.add(new Message("ein Kondom kaputt gemacht",date2,user));
        messages.add(new Message("ein Sammelkartenspiel aktiv gespielt",date2,user));
        messages.add(new Message("ein so gutes Verhältnis zu meinem Partner gehabt, dass wir die Badezimmertür offen gelassen haben",date2,user));
        messages.add(new Message("ein Tagebuch geführt",date2,user));
		messages.add(new Message("ein pinkes Polo-Shirt getragen",date3,user));
		messages.add(new Message("eine Brille ohne Gläser getragen",date3,user));
        messages.add(new Message("eine Datingwebsite besucht",date,user));
        messages.add(new Message("eine Diät gemacht",date,user));
        messages.add(new Message("eine Frau oral befriedigt",date2,user));
        messages.add(new Message("eine Happy-End-Massage bekommen",date,user));
        messages.add(new Message("eine Kündigung erhalten",date2,user));
		messages.add(new Message("eine Milf angebaggert",date3,user));
        messages.add(new Message("eine Nacht im Krankenhaus verbracht",date,user));
        messages.add(new Message("eine Panne gehabt, weil ich vergessen hatte zu tanken",date2,user));
        messages.add(new Message("eine perfekte Woche gehabt",date,user));
		messages.add(new Message("eine Prüfung geschrieben, ohne gelernt zu haben",date3,user));
        messages.add(new Message("eine rote Ampel überfahren",date,user));
        messages.add(new Message("eine Schlägerei gehabt",date,user));
        messages.add(new Message("eine Schlägerei mit einem Türsteher gehabt",date2,user));
        messages.add(new Message("eine Sonnenbrille angezogen um, jemandem auf die Brüste zu gaffen",date,user));
        messages.add(new Message("eine Unterschrift gefälscht",date,user));
		messages.add(new Message("eine Vorlesung geschwänzt",date3,user));
        messages.add(new Message("eine Zigarre geraucht",date2,user));
        messages.add(new Message("eine Zigarette am falschen Ende angezündet",date,user));
        messages.add(new Message("einen Abend allein im Club verbracht",date2,user));
		messages.add(new Message("einen Alligator/ein Krokodil in der Wildnis gesehen",date3,user));
		messages.add(new Message("einen Anwalt gebraucht",date3,user));
        messages.add(new Message("einen Arsch geleckt",date,user));
        messages.add(new Message("einen Autounfall verursacht",date,user));
		messages.add(new Message("einen BH getragen",date3,user));
        messages.add(new Message("einen Blowjob bekommen",date,user));
        messages.add(new Message("einen Dildo in der Hand gehalten",date2,user));
        messages.add(new Message("einen Dreier gehabt",date,user));
        messages.add(new Message("einen elektrischen Zaun angefasst",date,user));
        messages.add(new Message("einen falschen Ausweis benutzt",date,user));
        messages.add(new Message("einen Fickfreund / eine Fickfreundin gehabt",date,user));
        messages.add(new Message("einen Film illegal heruntergeladen",date,user));
        messages.add(new Message("einen ganzen Tag lang Videospiele gespielt",date2,user));
		messages.add(new Message("einen Gay-Club besucht",date3,user));
        messages.add(new Message("einen Haushaltsgegenstand als Sexspielzeug verwendet",date,user));
		messages.add(new Message("einen Lehrer erpresst",date3,user));
        messages.add(new Message("einen Lesbenporno geschaut",date,user));
        messages.add(new Message("einen Neujahrsvorsatz tatsächlich eingehalten",date2,user));
        messages.add(new Message("einen One-Night-Stand gehabt",date2,user));
        messages.add(new Message("einen Orgasmus vorgetäuscht",date,user));
        messages.add(new Message("einen Porno gedreht",date,user));
        messages.add(new Message("einen Porno geschaut",date,user));
        messages.add(new Message("einen Porno mit einem Freund vom gleichen Geschlecht geschaut",date,user));
        messages.add(new Message("einen Prominenten getroffen",date2,user));
		messages.add(new Message("einen Radiergummi vollständig aufgebraucht",date3,user));
        messages.add(new Message("einen Schwangerschaftstest gemacht",date,user));
        messages.add(new Message("einen Schwulenporno geschaut",date,user));
        messages.add(new Message("einen Spiegel benutzt, um meine Intimzone zu betrachten",date2,user));
        messages.add(new Message("einen Stripclub besucht",date,user));
        messages.add(new Message("einen Swinger-Club besucht",date2,user));
        messages.add(new Message("einen Tag ohne Unterwäsche verbracht",date2,user));
        messages.add(new Message("einen Tampon in meine Nase gesteckt",date2,user));
        messages.add(new Message("einen Tanga getragen",date2,user));
		messages.add(new Message("einen Taser benutzt",date3,user));
        messages.add(new Message("erotische Unterwäsche getragen",date2,user));
        messages.add(new Message("erst im Zug bemerkt, dass ich gar kein Ticket hatte",date2,user));
		messages.add(new Message("Essen ins Kino geschmuggelt",date3,user));
        messages.add(new Message("etwas anderes als Klopapier benutzt",date2,user));
        messages.add(new Message("etwas besessen, was ich immer versteckt habe, wenn Freunde da waren",date2,user));
        messages.add(new Message("etwas geklaut",date,user));
        messages.add(new Message("etwas beim Sex getan, womit ich mich völlig blamiert habe",date2,user));
        messages.add(new Message("etwas illegales gekauft",date,user));
        messages.add(new Message("Fantasien mit einem (ehemaligen) Lehrer gehabt",date,user));
		messages.add(new Message("Fussball langweilig gefunden",date3,user));
        messages.add(new Message("für eine Raubkopie Geld zahlen müssen",date,user));
        messages.add(new Message("für jemanden gekocht",date2,user));
        messages.add(new Message("für jemanden gestripped",date,user));
        messages.add(new Message("für Sex bezahlt",date,user));
        messages.add(new Message("für Sex Geld angenommen",date,user));
		messages.add(new Message("gegen den Wind gepinkelt",date3,user));
        messages.add(new Message("gehofft, in einer Runde dieses Spiels nicht als einziger trinken zu müssen",date2,user));
		messages.add(new Message("Geld als Strassenkünstler verdient",date3,user));
		messages.add(new Message("gelogen, um an einen Job zu kommen",date3,user));
		messages.add(new Message("gelogen, um bei den Eltern eines Freundes / einer Freundin gut anzukommen",date3,user));
        messages.add(new Message("gelogen, um einen Freund beim Fremdgehen zu decken",date,user));
        messages.add(new Message("geniest und die Hand an jemand anderem abgewischt",date2,user));
        messages.add(new Message("gepopelt und es dann gegessen",date2,user));
        messages.add(new Message("gesagt bekommen, ich sei zu schnell gekommen",date2,user));
        messages.add(new Message("(halb)nackt vor einer Webcam gesessen",date2,user));
        messages.add(new Message("heimlich das Getränk eines anderen getrunken",date2,user));
        messages.add(new Message("heimlich das Handy meines Partners durchsucht",date,user));
        messages.add(new Message("halb nackt für jemanden die Tür aufgemacht (z.B. den Postboten)",date2,user));
        messages.add(new Message("hinter dem Kühlschrank sauber gemacht",date2,user));
        messages.add(new Message("\"Ich liebe dich\" gesagt, nur um flachgelegt zu werden",date,user));
        messages.add(new Message("illegale Drogen genommen",date,user));
        messages.add(new Message("im Club jemandem einen geblasen / einen geblasen bekommen",date2,user));
        messages.add(new Message("im Schwimmbad ins Wasser gepinkelt",date,user));
        messages.add(new Message("im Stehen gepinkelt",date2,user));
		messages.add(new Message("im Unterricht heimlich Musik gehört",date3,user));
        messages.add(new Message("in den Spiegel geschaut und mich selbst geil gefunden",date2,user));
        messages.add(new Message("in der Öffentlichkeit in die Hose gepinkelt",date2,user));
        messages.add(new Message("in die Dusche gepinkelt",date2,user));
        messages.add(new Message("in ein Auto gekotzt",date,user));
        messages.add(new Message("in eine Flasche gepinkelt",date2,user));
        messages.add(new Message("in einem Raum versucht zu schlafen, während andere Sex hatten",date2, user));
        messages.add(new Message("in einem Sex-Shop etwas gekauft",date2,user));
        messages.add(new Message("in einer Vorlesung / im Unterricht geschlafen",date2,user));
		messages.add(new Message("in Klamotten geduscht",date3,user));
        messages.add(new Message("im Bikini Autos gewaschen",date2,user));
        messages.add(new Message("im Bus / Zug den Platz gewechselt, um neben einer attraktiven Person zu sitzen",date2,user));
        messages.add(new Message("jemand anderen beim Sex erwischt",date,user));
        messages.add(new Message("jemand anderen beim Sex gehört",date,user));
        messages.add(new Message("jemandem die falsche Nummer gegeben",date,user));
        messages.add(new Message("jemandem die Füße geküsst",date2,user));
        messages.add(new Message("jemandem einen Blowjob gegeben",date,user));
        messages.add(new Message("jemandem etwas gebrochen",date,user));
		messages.add(new Message("jemanden bei ebay abgezogen",date3,user));
        messages.add(new Message("jemanden bei etwas versautem erwischt",date2,user));
		messages.add(new Message("jemanden bei Facebook blockiert",date3,user));
        messages.add(new Message("jemanden beim Autofahren befriedigt",date,user));
        messages.add(new Message("jemanden beim Masturbieren beobachtet",date2,user));
        messages.add(new Message("jemanden beim Pornoschauen erwischt",date2,user));
        messages.add(new Message("jemanden entjungfert",date2,user));
        messages.add(new Message("jemanden im Schlaf angemalt",date,user));
        messages.add(new Message("jemanden in einer Beziehung betrogen",date,user));
        messages.add(new Message("jemanden nach der Nummer gefragt und mich nie gemeldet",date2,user));
        messages.add(new Message("jemanden Shots aus meinem Bauchnabel trinken lassen",date2,user));
        messages.add(new Message("jemanden vom gleichen Geschlecht geküsst",date,user));
        messages.add(new Message("Klamotten ohne Unterwäsche getragen",date,user));
        messages.add(new Message("Kondome gekauft",date2,user));
        messages.add(new Message("länger als eine Stunde Sex gehabt",date,user));
		messages.add(new Message("Leute online auf deren Rechtschreibfehler hingewiesen",date3,user));
        messages.add(new Message("Liebeskugeln verwendet",date2,user));
        messages.add(new Message("mehr als 5 mal an einem Tag masturbiert",date2,user));
        messages.add(new Message("mehr als 10 Stellungen ausprobiert",date2,user));
        messages.add(new Message("mehrere Tage hintereinander dieselbe Unterwäsche getragen",date,user));
        messages.add(new Message("mein Handy verloren",date,user));
        messages.add(new Message("meinem Partner einen versauten Spitznamen gegeben",date2,user));
        messages.add(new Message("meinen Brüsten Namen gegeben",date2,user));
		messages.add(new Message("meinen Chef angelogen",date3,user));
        messages.add(new Message("meinen Eltern die Frage, ob ich noch Jungfrau sei, beantworten müssen",date2,user));
		messages.add(new Message("meinen Facebook-Account gelöscht",date3,user));
        messages.add(new Message("meinen Führerschein abgeben müssen",date,user));
        messages.add(new Message("meinen Hintern eingescannt",date2,user));
        messages.add(new Message("meinen Partner beim Sex gefilmt",date,user));
        messages.add(new Message("meinen Penis ausgemessen",date2,user));
        messages.add(new Message("mit einem Kuscheltier geredet",date2,user));
        messages.add(new Message("mit einer elektrischen Zahnbürste onaniert",date2,user));
        messages.add(new Message("mit jemand anderem einen Porno geschaut",date,user));
        messages.add(new Message("mit jemandem aus dieser Runde rummachen wollen",date,user));
        messages.add(new Message("mit jemandem geschlafen, den ich aus dem Internet kannte",date,user));
        messages.add(new Message("mit jemandem geschlafen, den ich hässlich fand",date,user));
        messages.add(new Message("mit jemandem geschlafen, den ich kürzer als 1 Stunde kannte",date,user));
        messages.add(new Message("mit jemandem rumgemacht, der in einer festen Beziehung war",date2,user));
        messages.add(new Message("mit jemandem rumgemacht, ohne deren/dessen Namen zu kennen",date,user));
        messages.add(new Message("mit jemandem Sex gehabt, der mindestens 10 Jahre älter war als ich",date,user));
        messages.add(new Message("mit jemandem vom anderen Geschlecht geduscht",date,user));
        messages.add(new Message("mit jemandem vom selben Geschlecht geduscht",date,user));
        messages.add(new Message("mit Lebensmitteln masturbiert",date,user));
        messages.add(new Message("mit mehr als einer Person am Abend rumgemacht",date,user));
        messages.add(new Message("mit sexuellen Gefälligkeiten für etwas bezahlt",date2,user));
        messages.add(new Message("Musik illegal heruntergeladen",date,user));
        messages.add(new Message("nach dem Sex geweint",date,user));
        messages.add(new Message("nach einem Friseurbesuch geweint",date2,user));
        messages.add(new Message("nachmittags Assi-TV geschaut",date2,user));
        messages.add(new Message("Nachrichten meines Partners ignoriert, um in Ruhe zocken zu können",date,user));
        messages.add(new Message("nachts gebadet",date2,user));
        messages.add(new Message("nackt geschlafen",date2,user));
		messages.add(new Message("nackt im See / Freibad gebadet",date3,user));
        messages.add(new Message("Nackbilder einer bestimmten Person gesucht",date2,user));
        messages.add(new Message("Nacktbilder geschickt bekommen",date2,user));
        messages.add(new Message("Nacktbilder verschickt",date,user));
        messages.add(new Message("Nackbilder von mir selbst gemacht",date,user));
		messages.add(new Message("Pfefferspray benutzt",date3,user));
        messages.add(new Message("Pokémon gespielt",date2,user));
        messages.add(new Message("Pornohefte zuhause versteckt",date2,user));
        messages.add(new Message("Schadenfreude verspürt, als jemand anderem etwas schlimmes passiert ist",date2,user));
		messages.add(new Message("schlafgewandelt",date3,user));
		messages.add(new Message("Schnecken gegessen",date3,user));
        messages.add(new Message("Sex auf einem Festival gehabt",date,user));
        messages.add(new Message("Sex auf einer Party gehabt",date,user));
        messages.add(new Message("Sex gehabt",date,user));
        messages.add(new Message("Sex gehabt, der kürzer als 10 Minuten dauerte",date,user));
        messages.add(new Message("Sex gehabt, der länger als 1 Stunde dauerte",date,user));
        messages.add(new Message("Sex gehabt, während andere Personen im Raum waren",date2,user));
        messages.add(new Message("Sex im Bett eines Verwandten gehabt",date,user));
        messages.add(new Message("Sex im Bett meiner Eltern gehabt",date2,user));
        messages.add(new Message("Sex im Flugzeug gehabt",date2,user));
        messages.add(new Message("Sex im Freien gehabt und mich dabei erwischen lassen",date2,user));
        messages.add(new Message("Sex in der Öffentlichkeit gehabt",date,user));
        messages.add(new Message("Sex in einem Auto gehabt",date,user));
        messages.add(new Message("Sex in einer Umkleidekabine gehabt",date,user));
		messages.add(new Message("Sex mit einer verheirateten Person gehabt",date3,user));
        messages.add(new Message("Sex mit der Person links von mir gehabt",date,user));
        messages.add(new Message("Sex mit der Person rechts von mir gehabt",date,user));
        messages.add(new Message("Sex mit der/dem Ex gehabt",date,user));
        messages.add(new Message("Sex mit einer Frau gehabt",date,user));
        messages.add(new Message("Sex mit einer Prostituierten gehabt",date,user));
        messages.add(new Message("Sex mit einem Mann gehabt",date,user));
        messages.add(new Message("Sex mit Zwillingen gehabt",date,user));
        messages.add(new Message("Sex vor Zuschauern gehabt",date,user));
        messages.add(new Message("Sex wegen einer Dating-App gehabt",date,user));
        messages.add(new Message("Sexspielzeug benutzt",date,user));
        messages.add(new Message("Sexspielzeug von anderen Leuten benutzt",date2,user));
        messages.add(new Message("Sexspielzeug von anderen Leuten gefunden",date2,user));
        messages.add(new Message("Sexspielzeug vor meinen Eltern versteckt",date2,user));
        messages.add(new Message("Shots aus einem Bauchnabel getrunken",date,user));
        messages.add(new Message("Silikonbrüste berührt",date2,user));
        messages.add(new Message("Smarties nach Farbe sortiert",date3,user));
        messages.add(new Message("so getan, als ob ich betrunken wäre", date2, user));
        messages.add(new Message("so viel getrunken, dass ich nicht mehr nach Hause gefunden habe",date2,user));
        messages.add(new Message("so laut über jemanden gelästert, dass der es mitbekommen hat",date2,user));
        messages.add(new Message("Sperma geschmeckt",date,user));
        messages.add(new Message("Strapse getragen",date2,user));
        messages.add(new Message("Strippoker gespielt",date,user));
        messages.add(new Message("Telefonsex gehabt",date,user));
        messages.add(new Message("Tierfutter gegessen",date2,user));
        messages.add(new Message("um Sex gebettelt",date2,user));
        messages.add(new Message("unter der Dusche gesungen",date,user));
        messages.add(new Message("über einen Freund gedacht, dass dessen Eltern bei der Erziehung versagt haben",date2,user));
        messages.add(new Message("über einen Partnertausch nachgedacht",date2,user));
		messages.add(new Message("über jemanden aus dieser Runde fantasiert",date3,user));
        messages.add(new Message("über mein Alter gelogen",date,user));
        messages.add(new Message("überlegt, mir ein Tattoo stechen zu lassen",date2,user));
        messages.add(new Message("versucht, mir ein Muster in den Intimbereich zu rasieren",date2,user));
        messages.add(new Message("versucht, einen Apfelkuchen zu vögeln",date2,user));
        messages.add(new Message("versucht, das Alphabet zu rülpsen",date,user));
		messages.add(new Message("versucht, jemanden zu beeindrucken und mich dabei verletzt",date3,user));
        messages.add(new Message("versucht, Marihuana anzubauen",date,user));
        messages.add(new Message("versucht, mit einem gefälschten Geldschein zu bezahlen",date2,user));
        messages.add(new Message("versucht, mit meinem Partner einen Porno nachzuspielen",date2,user));
        messages.add(new Message("versucht, vor der Polizei wegzulaufen",date2,user));
        messages.add(new Message("Viagra genommen",date2,user));
        messages.add(new Message("vor 13 Uhr soviel getrunken, dass ich sturzbesoffen war",date2,user));
		messages.add(new Message("vor der Schule gestanden, weil ich verpeilt hatte, dass Sonntag / Feiertag ist.",date3,user));
        messages.add(new Message("vorgegeben, homosexuell zu sein, um in Ruhe gelassen zu werden",date2,user));
        messages.add(new Message("wegen einer Spinne gekreischt",date2,user));
        messages.add(new Message("wegen eines Katers geschwänzt",date2,user));
		messages.add(new Message("Witze über Religion gemacht",date3,user));
        messages.add(new Message("World of Warcraft gespielt",date2,user));
        messages.add(new Message("zum \"Idiotentest\" gehen müssen",date2,user));



        return messages;
    }

    public static String getInputCommand(Message message, String tableName) {
        // INSERT INTO tableName VALUES('text','author','date_added');
        String statement = "INSERT INTO "+tableName+" VALUES('"+message.getText()+"','"+message.getAuthor()+"','"+message.getDate()+"');";
        return statement;
    }
}
